config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="user")),
    path("survey/", include("surveys.urls", namespace="survey")),
    path("organization/", include("organizations.urls", namespace="organization")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

surveys/urls.py
from django.urls import path
from . import views as survey_view

app_name = "survey"

urlpatterns = [
    path("new/", survey_view.SurveyView.as_view(), name="newsurvey"),
    path("list/", survey_view.SurveyListView.as_view(), name="list"),
    path("confirm/", survey_view.SurveyConfirmView.as_view(), name="confirm"),
]

surveys/models.py
from django.db import models
from core import models as core_model
from datetime import datetime
from django.utils.dateformat import DateFormat

# Create your models here.


class Survey(core_model.TimeStampedModel):

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="user"
    )
    date = models.DateField(default=DateFormat(datetime.now()).format("Y-m-d"))
    question1 = models.BooleanField(default=False)
    question2 = models.BooleanField(default=False)
    question3 = models.BooleanField(default=False)
    question4 = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date) + " : " + self.user.username

    class Meta:
        ordering = ["user"]


surveys/forms.py
from django import forms
from . import models


class SurveyForm(forms.ModelForm):
    class Meta:
        model = models.Survey
        fields = (
            "user",
            "date",
            "question1",
            "question2",
            "question3",
            "question4",
        )
        widgets = {
            "user": forms.HiddenInput(),
            "date": forms.HiddenInput(),
        }

        labels = {
            "question1": "최근에 이태원에 다녀온적이 있나요?",
            "question2": "최근에 해외에 다녀온적이 있나요?",
            "question3": "최근에 기침 등의 증상이 있나요?",
            "question4": "성실하게 답변하였나요?",
        }

    def save(self, *args, **kwargs):
        survey = super().save()
        survey.save()

surveys/views.py
from django.shortcuts import render, reverse
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.views.generic import FormView, DetailView, UpdateView, ListView, View
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.paginator import Paginator
from . import forms, models
from pushmsg import send_msg
from organizations import models as organization_model
from users import models as user_model
from users import mixins

# Create your views here.


class SurveyView(mixins.LoggedInOnlyView, FormView):

    template_name = "surveys/newSurvey.html"
    form_class = forms.SurveyForm

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        context = self.get_context_data(**kwargs)
        context["todate"] = DateFormat(datetime.now()).format("Y-m-d")
        return self.render_to_response(context)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:core")

    def get_initial(self):
        initial = super().get_initial()
        initial["user"] = self.request.user
        initial["date"] = DateFormat(datetime.now()).format("Y-m-d")
        return initial

    def form_valid(self, form):

        moral = form.cleaned_data.get("question4")

        survey = models.Survey.objects.filter(
            date=DateFormat(datetime.now()).format("Y-m-d")
        ).filter(user=self.request.user)

        if moral:

            if len(survey) == 0:
                messages.add_message(self.request, messages.INFO, "감사합니다!")
                form.save()

            else:
                messages.add_message(self.request, messages.ERROR, "오늘은 이미 참여하였습니다")

        else:
            messages.add_message(self.request, messages.ERROR, "당신의 양심은 안녕하십니까?")

        return super().form_valid(form)


class SurveyListView(mixins.LoggedInOnlyView, mixins.MasterUserOnlyView, ListView):
    def get(self, request):

        result = []

        organization = organization_model.Organization.objects.filter(
            master=self.request.user
        ).values("users__username", "users__nickname")

        for o in organization:

            survey = models.Survey.objects.filter(
                user__username=o["users__username"],
                date=DateFormat(datetime.now()).format("Y-m-d"),
            )

            if len(survey) == 1:
                result.append(survey[0])

            else:
                temp = {"user": o["users__nickname"], "option": True}
                result.append(temp)

        return render(request, "surveys/surveylist.html", {"surveys": result},)


class SurveyConfirmView(View):
    def get(self, request):

        organization = organization_model.Organization.objects.filter(
            master=self.request.user
        ).values("users__username", "users__nickname")

        for o in organization:

            survey = models.Survey.objects.filter(
                user__username=o["users__username"],
                date=DateFormat(datetime.now()).format("Y-m-d"),
            )

            if len(survey) == 1:
                pass

            else:
                send_msg(o["users__username"])

        return render(request, "partial/blank.html")

templates/surveys/newSurvey.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div
    class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <div class="my-10">
        <span class="text-xl">TODAY: {{todate}}</span>
    </div>

    <form action="{% url "survey:newsurvey" %}" method="POST">

        {% csrf_token %}

        {{form.user}}
        {{form.date}}

        <table class="table-auto w-9/12 mx-auto my-10">
            <thead>
              <tr>
                <th class="px-4 py-2">질문</th>
                <th class="px-4 py-2">응답</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="border px-4 py-2">{{form.question1.label}}</td>
                <td class="border px-4 py-2">{{form.question1}}</td>
              </tr>
              <tr>
                <td class="border px-4 py-2">{{form.question2.label}}</td>
                <td class="border px-4 py-2">{{form.question2}}</td>
              </tr>
              <tr>
                <td class="border px-4 py-2">{{form.question3.label}}</td>
                <td class="border px-4 py-2">{{form.question3}}</td>
              </tr>
              <tr>
                <td class="border px-4 py-2"><span class="text-red-500 font-extrabold">[필수] </span>{{form.question4.label}}</td>
                <td class="border px-4 py-2">{{form.question4}}</td>
              </tr>
              <tr>
                <td colspan="2" class="border px-4 py-2"><button class="hover:text-gray-600">제출하기</button></td>
              </tr>
            </tbody>
          </table>

    </form>

</div>

{% endblock content %}

templates/surveys/surveylist.html
{% extends "base.html"%} {% block content %}

<div
  class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">
  <table class="table-auto mx-auto my-5 w-4/5">
    <thead>
      <tr>
        <th class="px-4 py-2">USER</th>
        <th class="px-4 py-2">이태원</th>
        <th class="px-4 py-2">해외출국</th>
        <th class="px-4 py-2">증상여부</th>
      </tr>
    </thead>
    <tbody>
      {% for survey in surveys %}
      <span>{% include "partial/survey_card.html" with survey=survey %}</span>
      {% endfor %}
      <tr>
        <td colspan="4" class="border px-4 py-2"><a href="{% url "survey:confirm" %}" class="hover:text-gray-500"
            onclick="">미응답자 알림 보내기</a></td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}