config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="user")),
    path("survey/", include("surveys.urls", namespace="survey")),
    path("organization/", include("organizations.urls", namespace="organization")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

users/urls.py
from django.urls import path
from . import views as user_view

app_name = "user"

urlpatterns = [
    path("signup/", user_view.SignUpView.as_view(), name="signup"),
    path("login/", user_view.LoginView.as_view(), name="login"),
    path("logout/", user_view.logout_view, name="logout"),
    path(
        "verify/<str:key>/",
        user_view.complete_verification,
        name="complete_verification",
    ),
    path("<int:pk>/", user_view.UserProfileView.as_view(), name="profile"),
    path(
        "update-profile/", user_view.UpdateProfileView.as_view(), name="updateprofile"
    ),
    path(
        "join-organization/",
        user_view.JoinOrganizationView.as_view(),
        name="joinorganization",
    ),
]

users/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
import uuid
from emails import sendVerifyEmail
from core import models as core_model

# Create your models here.


class AbstractItem(core_model.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Job(AbstractItem):

    """ Job Model Definition """

    class Meta:
        verbose_name = "Job"


class User(AbstractUser):

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"
    GENDER_CHOICE = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    nickname = models.CharField(max_length=20, blank=True)
    age = models.IntegerField(
        default=15, validators=[MinValueValidator(15), MaxValueValidator(99)]
    )
    gender = models.CharField(choices=GENDER_CHOICE, default=GENDER_MALE, max_length=6)
    job = models.ForeignKey(
        "Job", related_name="job", on_delete=models.CASCADE, null=True
    )
    desired_organization = models.ManyToManyField(
        "organizations.Organization", related_name="desired_organization", blank=True
    )

    email_secret = models.CharField(
        max_length=20, default=uuid.uuid4().hex[:20], blank=True
    )
    email_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.username + "(" + self.nickname + ")"

    def verify_email(self):
        if self.email_verified is False:
            sendVerifyEmail(self.email, self.email_secret)
            self.save()
        return

    def get_absolute_url(self):
        return reverse("user:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from organizations import models as organization_model
from . import models


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User

        fields = (
            "email",
            "nickname",
            "password",
            "re_password",
            "gender",
            "age",
            "job",
        )

        widgets = {
            "email": forms.EmailInput(attrs={"placeholder": "email@naver.com"}),
            "nickname": forms.TextInput(attrs={"placeholder": "홍길동"}),
        }

        labels = {
            "email": "이메일",
            "nickname": "이름",
            "password": "비밀번호",
            "re_password": "비밀번호 확인",
            "gender": "성별",
            "age": "나이",
            "job": "직업",
        }

    password = forms.CharField(widget=forms.PasswordInput(), label="비밀번호")
    re_password = forms.CharField(widget=forms.PasswordInput(), label="비밀번호 확인")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("이미 가입한 사용자압니다", code="existing_user")
        except models.User.DoesNotExist:
            return email

    def clean_re_password(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if password != re_password:
            raise forms.ValidationError("패스워드가 일치하지 않습니다")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "이메일"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 다릅니다"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("해당 유저가 존재하지 않습니다"))


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = models.User

        fields = ("desired_organization",)

        widgets = {
            "desired_organization": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(OrganizationForm, self).__init__(*args, **kwargs)
        self.fields[
            "desired_organization"
        ].queryset = organization_model.Organization.objects.filter(isrecruited=True)

    def save(self, *args, **kwargs):
        user = super().save()
        user.save()

users/views.py
from django.shortcuts import redirect, reverse, render
from django.contrib.auth import login, logout, authenticate
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib import messages
from django import forms as django_forms
from . import forms, models, mixins


# Create your views here.


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            user.verify_email()
            messages.add_message(self.request, messages.INFO, "회원가입 완료!\n이메일 인증을 해주세요")
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:core")


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.add_message(self.request, messages.INFO, "환영합니다")
        else:
            messages.add_message(self.request, messages.ERROR, "로그인 실패")
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse_lazy("core:core")


def logout_view(request):
    logout(request)
    messages.add_message(request, messages.INFO, "안녕히가세요")
    return redirect(reverse("core:core"))


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        messages.add_message(request, messages.INFO, "인증을 완료하셨습니다!")
    except models.User.DoesNotExist:
        messages.add_message(request, messages.ERROR, "인증을 완료할 수 없습니다")
        pass
    return redirect(reverse("core:core"))


class UserProfileView(mixins.LoggedInOnlyView, mixins.VerifiedUserOnlyView, DetailView):

    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UpdateProfileView(
    mixins.LoggedInOnlyView, mixins.VerifiedUserOnlyView, UpdateView
):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "nickname",
        "age",
        "gender",
        "job",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        return form

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "수정 완료!")
        return self.request.user.get_absolute_url()


class JoinOrganizationView(
    mixins.LoggedInOnlyView, mixins.VerifiedUserOnlyView, UpdateView
):

    model = models.User
    form_class = forms.OrganizationForm
    template_name = "users/join-organization.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        return form

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "신청을 변경하였습니다")
        return reverse_lazy("core:core")

templates/users/join-organization.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    input {
        text-align: center;
    }
</style>

<div
    class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <div class="w-3/4 h-40 mx-auto my-10 p-5 rounded-xlg bg-red-100" style="overflow-y: scroll;">

        <p>그룹 가입 안내</p>

        <p>본 서비스는 가입신청 서비스로, 본인이 가입 희망하는 그룹을 골라 저장할 수 있습니다</p>

        <p>이후, 해당 그룹의 관리자가 승인하면 본인의 설문 기록을 조회할 수 있습니다</p>

        <p>승인 후에는 가입 신청을 취소하여도 그룹에는 남아있을 수도 있습니다</p>

        <p>정말 신청하시겠습니까?</p>

    </div>

    <div>
        <form>
            <input type="checkbox" name="agreement" id="agreement">
            <label for="agreement"><span class="text-red-500 font-bold">[필수]</span> 신청합니다</label>
        </form>
    </div>

    <form method="POST" action="{% url "user:joinorganization" %}" class="">

        {% csrf_token %}

        <h1 class="my-8 text-3xl text-blue-800">그룹 목록</h1>

        <div class="w-1/2 h-48 mx-auto my-10 py-5 border-2 rounded-xlg" style="overflow-y: scroll;">

            {{form.desired_organization}}

        </div>

        <button class="mb-6 text-xl hover:text-gray-500">신청하기</button>

    </form>

</div>


<script>
    document.addEventListener('submit', (ev) => {
        const check = document.getElementById("agreement")
        if (check.checked) {
            ;
        }
        else {
            ev.preventDefault();
            alert("신청에 동의해주세요")
        }
    })
</script>


{% endblock content %}

templates/users/login.html
{% extends "base.html" %}


{% block content %}

<style>

    input{
        margin: 0 auto;
        margin-top: 30px;
        margin-bottom: 30px;

        padding-left: 30px;

        display: block;
        
        height: 70px;
        width: 50%;
        line-height: 30px;

        border-radius: 50px;

        background-color: #EEEEEE;
    }

    input:focus{
        outline: none;
    }

    button{
        margin: 0 auto;
        margin-top: 30px;
        margin-bottom: 30px;
        
        padding-left: 0;

        display: block;
        
        width: 50%;
        height: 70px;
        line-height: 30px;

        border-radius: 50px;

        background-color: #A8C1FF;
    }

    button:hover{
        background-color: #7DA2FE;
    }

</style>

<div class="container my-10 mx-auto text-center border-2 border-black w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <h1 class="my-10 text-4xl text-blue-800">LOGIN</h1>

    <form method="POST" action="{% url "user:login" %}" class="my-20">
        {% csrf_token %}

        {{form.email}}
        <span class="font-bold text-red-600 text-center">{{form.email.errors}}</span>

        {{form.password}}
        <span class="font-bold text-red-600 text-center">{{form.password.errors}}</span>

        <button>로그인</button>
    </form>

    <p class="my-16 italic">아직 계정이 없으시면 <a href="{% url "user:signup" %}" class="text-blue-400 font-bold text-xl hover:text-blue-500">여기</a>를 눌러서 계정을 만드세요!</p>
</div>

{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    input {
        text-align: center;
    }
</style>

<div
    class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <h1 class="mx-auto my-5 text-6xl text-red-600"><i class="fas fa-user-circle"></i></h1>

    <form method="POST" action="{% url "user:updateprofile" %}" class="">

        {% csrf_token %}

        <table class="table-auto w-9/12 mx-auto my-10">
            <tbody>
                <tr>
                    <td class="border px-4 py-2">닉네임</td>
                    <td class="border px-4 py-2">
                        {{form.nickname}}
                    </td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">성별</td>
                    <td class="border px-4 py-2">
                        {{form.gender}}
                    </td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">나이</td>
                    <td class="border px-4 py-2">{{form.age}}</td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">직업</td>
                    <td class="border px-4 py-2">{{form.job}}</td>
                </tr>
                <tr>
                    <td colspan="2" class="border px-4 py-2"><button class="hover:text-gray-500">수정하기</button></td>
                </tr>
            </tbody>
        </table>

    </form>

</div>

{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %} {% load static %} {% block content %}

<div
  class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

  <h1 class="mx-auto my-5 text-6xl text-blue-600"><i class="fas fa-user-circle"></i></h1>

  <table class="table-auto w-4/5 mx-auto my-10">
    <thead>
      <tr>
        <th class="px-4 py-2">분류</th>
        <th class="px-4 py-2">정보</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="border px-4 py-2">이름</td>
        <td class="border px-4 py-2">{{user_obj.nickname}}</td>
      </tr>
      <tr>
        <td class="border px-4 py-2">이메일</td>
        <td class="border px-4 py-2">{{user_obj.email}}</td>
      </tr>
      <tr>
        <td class="border px-4 py-2">성별</td>
        {% if user_obj.gender == "male" %}
        <td class="border px-4 py-2"><i class="fas fa-mars text-blue-500"></i> 남성</td>
        {% elif user_obj.gender == "female" %}
        <td class="border px-4 py-2"><i class="fas fa-venus text-pink-500"></i> 여성</td>
        {% else %}
        <td class="border px-4 py-2"><i class="fas fa-genderless"></i> 기타</td>
        {% endif %}
      </tr>
      <tr>
        <td class="border px-4 py-2">직업</td>
        <td class="border px-4 py-2">{{user_obj.job}}</td>
      </tr>
    </tbody>
  </table>

  {% if user_obj == user %}

  <a href="{% url "user:updateprofile" %}">
    <div class="w-1/2 h-20 flex mx-auto my-10 rounded-lg bg-orange-400 hover:bg-orange-500">
      <div class="items-center mx-auto my-auto text-xl">
        <i class="fas fa-user-shield"></i> 개인정보 수정
      </div>
    </div>
  </a>

  {% endif %}

</div>

{% endblock content %}