config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="user")),
    path("survey/", include("surveys.urls", namespace="survey")),
    path("organization/", include("organizations.urls", namespace="organization")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

organizations/urls.py
from django.urls import path
from . import views as organization_view

app_name = "organization"

urlpatterns = [
    path("menu/", organization_view.OrganizationMenuView.as_view(), name="menu"),
    path("new/", organization_view.OrganizationView.as_view(), name="neworganization"),
    path(
        "update-organization/<int:pk>/",
        organization_view.OrganizationUpdateView.as_view(),
        name="updateorganization",
    ),
    path("error/", organization_view.OrganizationUnvalidView.as_view(), name="unvalid"),
]

surveys/urls.py
from django.urls import path
from . import views as survey_view

app_name = "survey"

urlpatterns = [
    path("new/", survey_view.SurveyView.as_view(), name="newsurvey"),
    path("list/", survey_view.SurveyListView.as_view(), name="list"),
    path("confirm/", survey_view.SurveyConfirmView.as_view(), name="confirm"),
]

users/urls.py
from django.urls import path
from . import views as user_view

app_name = "user"

urlpatterns = [
    path("signup/", user_view.SignUpView.as_view(), name="signup"),
    path("login/", user_view.LoginView.as_view(), name="login"),
    path("logout/", user_view.logout_view, name="logout"),
    path(
        "verify/<str:key>/",
        user_view.complete_verification,
        name="complete_verification",
    ),
    path("<int:pk>/", user_view.UserProfileView.as_view(), name="profile"),
    path(
        "update-profile/", user_view.UpdateProfileView.as_view(), name="updateprofile"
    ),
    path(
        "join-organization/",
        user_view.JoinOrganizationView.as_view(),
        name="joinorganization",
    ),
]

templates/partial/blank.html
<script>
  const ips = document.getElementById("ipconfig").innerText;

  init = () => {
    location.href = `http://${ips}/`;
  };

  init();
</script>

templates/partial/footer.html
<div class="w-full text-center text-gray-600 border-t-2 border-gray-500">
  <ul>
    <a href="https://maplestory.nexon.com/Home/Main">
      <li>DEVELOPER: &copy; Min</li>
    </a>
    <li>ADDRESS: REP. of KOREA, Seoul</li>
    <li>TEL: 010-4033-0246</li>
    <li>EMAIL: 7cmdehdrb@naver.com</li>
  </ul>
</div>

templates/partial/messages.html
{% if messages %}
<ul class="absolute top- w-1/4 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="messages font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-full text-center {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partial/nav.html
{% load static %}

<div class="w-full flex h-20 bg-white border-b-2 border-gray-500">

    <a href="{% url "core:core" %}" class="pl-5 py-1 h-full">
        <img src="{% static "image/logo.svg" %}" alt="logo" class="h-full items-center justify-center">
        <!-- <i class="fas fa-virus-slash h-full items-center justify-center text-red-500 text-6xl"></i> -->
    </a>
    <ul class="w-full h-full flex justify-end items-center mr-2">
        <a href="{% url "survey:newsurvey" %}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10">설문참여</li>
        </a>
        <a href="{% url "organization:menu" %}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10">그룹관리</li>
        </a>
        {% if user.is_authenticated %}
        <a href="{% url "user:logout" %}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10">로그아웃</li>
        </a>
        <a href="{{user.get_absolute_url}}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10" id="userid">{{user.nickname}}</li>
        </a>
        {% else %}
        <a href="{% url "user:login" %}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10">로그인</li>
        </a>
        <a href="{% url "user:signup" %}" class="h-full border-b-8 border-white hover:border-gray-600 hover:bg-gray-100">
            <li class="flex h-full items-center justify-center sm:px-2 md:px-4 lg:px-6 xl: px-10">회원가입</li>
        </a>
        {% endif%}
    </ul>

</div>

templates/partial/survey_card.html
{% if survey.option %}

<tr>
  <td class="border px-4 py-2">{{survey.user}}</td>
  <td colspan="3" class="border px-4 py-2 text-red-500">NO DATA</td>
<tr>

{% else %}

<tr>
  <td class="border px-4 py-2">{{survey.user.nickname}}</td>
  <td class="border px-4 py-2">
    {% if survey.question1 %}
    <span class="text-green-500"><i class="fas fa-check-circle"></i></span>
    {% else %}
    <span class="text-red-500"><i class="fas fa-times-circle"></i></span>
    {% endif %}
  </td>
  <td class="border px-4 py-2">
    {% if survey.question2 %}
    <span class="text-green-500"><i class="fas fa-check-circle"></i></span>
    {% else %}
    <span class="text-red-500"><i class="fas fa-times-circle"></i></span>
    {% endif %}
  </td>
  <td class="border px-4 py-2">
    {% if survey.question3 %}
    <span class="text-green-500"><i class="fas fa-check-circle"></i></span>
    {% else %}
    <span class="text-red-500"><i class="fas fa-times-circle"></i></span>
    {% endif %}
  </td>
</tr>

{% endif %}