config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="user")),
    path("survey/", include("surveys.urls", namespace="survey")),
    path("organization/", include("organizations.urls", namespace="organization")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

organizations/urls.py
from django.urls import path
from . import views as organization_view

app_name = "organization"

urlpatterns = [
    path("menu/", organization_view.OrganizationMenuView.as_view(), name="menu"),
    path("new/", organization_view.OrganizationView.as_view(), name="neworganization"),
    path(
        "update-organization/<int:pk>/",
        organization_view.OrganizationUpdateView.as_view(),
        name="updateorganization",
    ),
    path("error/", organization_view.OrganizationUnvalidView.as_view(), name="unvalid"),
]

surveys/urls.py
from django.urls import path
from . import views as survey_view

app_name = "survey"

urlpatterns = [
    path("new/", survey_view.SurveyView.as_view(), name="newsurvey"),
    path("list/", survey_view.SurveyListView.as_view(), name="list"),
    path("confirm/", survey_view.SurveyConfirmView.as_view(), name="confirm"),
]

users/urls.py
from django.urls import path
from . import views as user_view

app_name = "user"

urlpatterns = [
    path("signup/", user_view.SignUpView.as_view(), name="signup"),
    path("login/", user_view.LoginView.as_view(), name="login"),
    path("logout/", user_view.logout_view, name="logout"),
    path(
        "verify/<str:key>/",
        user_view.complete_verification,
        name="complete_verification",
    ),
    path("<int:pk>/", user_view.UserProfileView.as_view(), name="profile"),
    path(
        "update-profile/", user_view.UpdateProfileView.as_view(), name="updateprofile"
    ),
    path(
        "join-organization/",
        user_view.JoinOrganizationView.as_view(),
        name="joinorganization",
    ),
]

organizations/models.py
from django.db import models
from django.urls import reverse
from core import models as core_model
from phone_field import PhoneField

# Create your models here.


class Organization(core_model.TimeStampedModel):

    name = models.CharField(max_length=20)
    master = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="master"
    )
    location = models.CharField(max_length=300)
    phone = PhoneField(help_text="Contact phone number")
    users = models.ManyToManyField("users.User", related_name="users", blank=True)
    isrecruited = models.BooleanField(default=True)

    def __str__(self):
        return self.name + "(Manager: " + self.master.nickname + ")"

    def get_absolute_url(self):
        return reverse("organization:organizationdetail", kwargs={"pk": self.pk})

organizations/forms.py
from django import forms
from users import models as user_model
from . import models


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = ("name", "master", "location", "phone", "users", "isrecruited")
        widgets = {
            "master": forms.HiddenInput(),
            "isrecruited": forms.HiddenInput(),
            "name": forms.TextInput(attrs={"placeholder": "주식회사 OOOO"}),
            "location": forms.TextInput(attrs={"placeholder": "서울특별시 강남구"}),
        }
        labels = {
            "name": "그룹이름",
            "location": "주소",
            "phone": "대표전화",
        }

    def save(self, *args, **kwargs):
        organization = super().save()
        organization.save()


class OrganizationUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = (
            "master",
            "name",
            "location",
            "phone",
            "isrecruited",
            "users",
        )
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "주식회사 OOOO"}),
            "location": forms.TextInput(attrs={"placeholder": "서울특별시 강남구"}),
            "users": forms.CheckboxSelectMultiple(),
        }
        labels = {
            "name": "그룹이름",
            "location": "주소",
            "phone": "대표전화",
        }

    def __init__(self, *args, **kwargs):
        super(OrganizationUpdateForm, self).__init__(*args, **kwargs)
        self.fields["users"].queryset = user_model.User.objects.filter(
            desired_organization__name=self["name"].value()
        )

    def get_initial(self):
        initial = super().get_initial()
        initial["master"] = self.request.user
        return initial

    def save(self, *args, **kwargs):
        organization = super().save()
        organization.save()

organizations/views.py
from django.shortcuts import render, reverse
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.views.generic import View, FormView, DetailView, UpdateView, ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.paginator import Paginator
from . import forms, models
from users import mixins

# Create your views here.


class OrganizationMenuView(mixins.LoggedInOnlyView, View):
    def get(self, request):

        result = None

        organization = models.Organization.objects.filter(
            master=self.request.user
        ).values("pk")

        if len(organization) != 0:
            result = organization[0]["pk"]

        return render(
            request, "organizations/organizationMenu.html", {"organizationpk": result},
        )


class OrganizationUnvalidView(View):
    def get(self, request):
        messages.add_message(self.request, messages.ERROR, "잘못된 접근입니다!")

        result = None

        organization = models.Organization.objects.filter(
            master=self.request.user
        ).values("pk")

        if len(organization) != 0:
            result = organization[0]["pk"]

        return render(
            request, "organizations/organizationMenu.html", {"organizationpk": result},
        )


class OrganizationView(
    mixins.LoginRequiredMixin, mixins.VerifiedUserOnlyView, FormView
):

    template_name = "organizations/newOrganization.html"
    form_class = forms.OrganizationForm

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse_lazy("organization:menu")

    def get_initial(self):
        initial = super().get_initial()
        initial["master"] = self.request.user
        initial["users"] = self.request.user
        return initial

    def form_valid(self, form):

        organization = models.Organization.objects.filter(
            master__username=self.request.user.username
        )

        if len(organization) != 0:
            messages.add_message(self.request, messages.ERROR, "그룹 생성은 1회로 제한됩니다")

        else:
            form.save()
            messages.add_message(self.request, messages.INFO, "성공적으로 그룹을 만들었습니다!")

        return super().form_valid(form)


class OrganizationUpdateView(
    mixins.LoggedInOnlyView, mixins.VerifiedUserOnlyView, UpdateView
):
    model = models.Organization
    template_name = "organizations/update-organization.html"
    form_class = forms.OrganizationUpdateForm

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "수정 완료!")
        return reverse_lazy("organization:menu")

templates/organizations/newOrganization.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>

    input{
        width: 90%;
        text-align: center;
    }

</style>

<div
    class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <div class="w-3/4 p-5 h-32 mx-auto my-10 bg-red-100" style="overflow-y: scroll;">

        <p>그룹 생성</p>

        <p>본 서비스는 그룹 관리 서비스입니다</p>

        <p>모든 사용자는 1인당 1개의 그룹을 생성할 수 있으며, 그룹의 삭제는 불가능합니다</p>

        <p>그룹의 관리자는 본인이 개설한 그룹의 가입 희망자를 조회, 가입 승인할 수 있으며, 성공적으로 가입을 완료한 사람의 설문을 조회할 수 있습니다</P>

    </div>

    <div>
      <input type="checkbox" name="agreement" id="agreement" style="width: auto;">
      <label for="agreement"><span class="text-red-500 font-bold">[필수]</span> 이용약관에 동의합니다</label>
    </div>

    <form action="{% url "organization:neworganization" %}" method="POST">

        {% csrf_token %}

        {{form.master}}
        {{form.isrecruited}}
        <span style="display: none;">{{form.users}}</span>

        <table class="table-auto w-9/12 mx-auto my-10">
            <tbody>
              <tr>
                <td class="border px-4 py-2">{{form.name.label}}</td>
                <td class="border px-4 py-2">{{form.name}}</td>
              </tr>
              <tr>
                <td class="border px-4 py-2">{{form.location.label}}</td>
                <td class="border px-4 py-2">{{form.location}}</td>
              </tr>
              <tr>
                <td class="border px-4 py-2">{{form.phone.label}}</td>
                <td class="border px-4 py-2">{{form.phone}}</td>
              </tr>
              <tr>
                <td colspan="2" class="border px-4 py-2"><button class="hover:text-gray-500">등록하기</button></td>
              </tr>
            </tbody>
          </table>

    </form>

</div>

<script>
  const phone0 = document.getElementById("id_phone_0");
  const phone1 = document.getElementById("id_phone_1");

  document.addEventListener('submit', (ev) => {
        const check = document.getElementById("agreement")
        if(check.checked){
            ;
        }
        else{
            ev.preventDefault();
            alert("이용약관에 동의해주세요")
        }
    })

  init = () => {
    phone0.placeholder = "대표번호";
    phone1.placeholder = "내선번호";
  }

  init();
</script>

{% endblock content %}

templates/organizations/organizationMenu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  #group {

    cursor: pointer;

  }
</style>

<h1 id="pk" style="display: none;">{{organizationpk}}</h1>

<div class="container my-10 mx-auto text-center w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">
  <a href="{% url "user:joinorganization" %}"
    class="block mx-auto w-4/5 py-10 my-5 text-4xl bg-pink-400 hover:bg-pink-500 rounded-xlg">
    <i class="fas fa-sign-in-alt"></i> 가입신청
  </a>
  <a href="{% url "organization:neworganization" %}"
    class="block mx-auto w-4/5 py-10 my-5 text-4xl bg-green-400 hover:bg-green-500 rounded-xlg">
    <i class="fas fa-user-plus"></i> 그룹생성
  </a>
  <div class="block mx-auto w-4/5 py-10 my-5 text-4xl bg-yellow-400 hover:bg-yellow-500 rounded-xlg" id="group">
    <i class="fas fa-users-cog"></i> 그룹관리
  </div>
  <a href="{% url "survey:list" %}"
    class="block mx-auto w-4/5 py-10 my-5 text-4xl bg-orange-400 hover:bg-orange-500 rounded-xlg">
    <i class="fas fa-search"></i> 설문보기
  </a>
</div>

<script>

  const group = document.getElementById("group");
  const pk = document.getElementById("pk").innerText;
  const ip = document.getElementById("ipconfig").innerText;

  group.addEventListener("click", (ev) => {
    ev.preventDefault();
    if (pk != "None") {
      location.href = `http://${ip}/organization/update-organization/${pk}/`;
    } else {
      location.href = `http://${ip}/organization/new/`;
    }
  })

</script>

{% endblock content %}

templates/organizations/update-organization.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    input {
        width: 90%;
        text-align: center;
    }
</style>

{% if organization.master == user %}

<div
    class="container my-10 mx-auto text-center border-2 border-black rounded-lg w-10/12 sm:w-9/12 md:w-8/12 lg:w-1/2 xl:w-5/12">

    <form method="POST" action="{% url "organization:updateorganization" organization.pk %}" class="">

        {% csrf_token %}

        <span style="display: none;">{{form.master}}</span>

        <table class="table-auto w-9/12 mx-auto my-10">
            <tbody>
                <tr>
                    <td class="border px-4 py-2">그룹이름</td>
                    <td class="border px-4 py-2">
                        {{form.name}}
                    </td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">주소</td>
                    <td class="border px-4 py-2">
                        {{form.location}}
                    </td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">대표전화</td>
                    <td class="border px-4 py-2">{{form.phone}}</td>
                </tr>
                <tr>
                    <td class="border px-4 py-2">회원 모집 여부</td>
                    <td class="border px-4 py-2">{{form.isrecruited}}</td>
                </tr>
                <tr>
                    <td colspan="2" class="border px-4 py-2">그룹 맴버</td>
                </tr>
                <tr>
                    <td colspan="2" class="border px-4 py-2">{{form.users}}</td>
                </tr>
                <tr>
                    <td colspan="2" class="border px-4 py-2"><button class="hover:text-gray-500">수정하기</button></td>
                </tr>
            </tbody>
        </table>

    </form>

</div>

<script>

    const li = document.getElementById("id_users");
    const me = document.getElementById("userid");
    const users = li.querySelectorAll("li")

    console.log(me.innerText)

    users.forEach(element => {
        console.log(element.innerText)
        if (element.innerText.replace(" ", "") == me.innerText) {
            element.style.display = "none";
        }
    });

</script>

<script>
    const phone0 = document.getElementById("id_phone_0");
    const phone1 = document.getElementById("id_phone_1");

    init = () => {
        phone0.placeholder = "대표번호";
        phone1.placeholder = "내선번호";
    }

    init();
</script>

{% else %}

<script>

    init = () => {
        location.href = "http://127.0.0.1:8000/organization/error/";
    }

    init();

</script>

{% endif %}

{% endblock content %}